TEST_CASES = [
    ([7, 'abcabca'], 5),
    ([8, 'abcdefgh'], 8),
    ([100,
    'mhnzadklojbuumkrxjayikjhwuxihgkinllackcavhjpxlydxcmhnzadklojbuumkrxjayikjhwuxihgkinllackcavhjpxlydxc'],
    51),
    ([99,
    'trolnjmzxxrfxuexcqpjvefndwuxwsukxwmjhhkqmlzuhrplrtrolnjmzxxrfxuexcqpjvefndwuxwsukxwmjhhkqmlzuhrplrm'],
    51),
    ([100,
    'yeywsnxcwslfyiqbbeoaawtmioksfdndptxxcwzfmrpcixjbzvicijofjrbcvzaedglifuoczgjlqylddnsvsjfmfsccxbdveqgu'],
    100),
    ([8, 'aaaaaaaa'], 5),
    ([4, 'abab'], 3),
    ([7, 'ababbcc'], 6),
    ([7, 'abcaabc'], 7),
    ([10, 'aaaaaaaaaa'], 6),
    ([6, 'aabbbb'], 6),
    ([6, 'abbbba'], 6),
    ([9, 'abcdeabcd'], 9),
    ([10, 'abcdabcefg'], 10),
    ([9, 'aaaaaaaaa'], 6),
    ([10, 'ababababab'], 7),
    ([9, 'zabcdabcd'], 9),
    ([5, 'aaaaa'], 4),
    ([10, 'adcbeadcfg'], 10),
    ([12, 'abcabcabcabc'], 7),
    ([16, 'aaaaaaaaaaaaaaaa'], 9),
    ([4, 'aaaa'], 3),
    ([17, 'ababababzabababab'], 14),
    ([10, 'abcabcabca'], 8),
    ([7, 'dabcabc'], 7),
    ([6, 'aaaaaa'], 4),
    ([5, 'abcbc'], 5),
    ([7, 'aabaaaa'], 7),
    ([100,
    'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'],
    51),
    ([6, 'ablfab'], 6),
    ([8, 'abcdefef'], 8),
    ([5, 'aavaa'], 5),
    ([1, 'a'], 1),
    ([10, 'abcabcdddd'], 8),
    ([16, 'aaaaaabbaaaaaabb'], 9),
    ([17, 'abcdefggggglelsoe'], 17),
    ([17, 'abcdefgggggabcdef'], 17),
    ([27, 'aaaaaaaaaaaaaaaaaaaaaaaaaaa'], 15),
    ([8, 'abbbbbbb'], 8),
    ([2, 'aa'], 2),
    ([5, 'baaaa'], 5),
    ([10, 'abcdeeeeee'], 10),
    ([12, 'aaaaaaaaaaaa'], 7),
    ([6, 'abcabd'], 6),
    ([10, 'ababcababc'], 6),
    ([16, 'bbbbbbaaaaaaaaaa'], 14),
    ([10, 'bbbbbbbbbc'], 7),
    ([9, 'asdfpasdf'], 9),
    ([9, 'baaaabaaa'], 9),
    ([11, 'abcabcabcab'], 9),
    ([10, 'abccaaaaba'], 10),
    ([8, 'abbbbbba'], 8),
    ([8, 'aaaaaass'], 6),
    ([20, 'hhhhhhhhhhhhhhhhhhhh'], 11),
    ([8, 'aabcabca'], 8),
    ([6, 'ababab'], 5),
    ([8, 'ababcdef'], 7),
    ([8, 'abababab'], 5),
    ([14, 'abcdefgabcdepq'], 14),
    ([6, 'abcaca'], 6),
    ([11, 'ababababccc'], 8),
    ([8, 'ababcabc'], 7),
    ([20, 'aabaabaabaabaabaabaa'], 12),
    ([20, 'abcdabcdeeeeeeeeabcd'], 17),
    ([9, 'asdfgasdf'], 9),
    ([10, 'avavavavbc'], 7),
    ([63, 'jhkjhadlhhsfkadalssaaggdagggfahsakkdllkhldfdskkjssghklkkgsfhsks'], 63),
    ([3, 'aaa'], 3),
    ([13, 'aabbbkaakbbbb'], 13),
    ([7, 'abababa'], 6),
    ([6, 'ajkoaj'], 6),
    ([7, 'abcdbcd'], 7),
    ([46, 'kgadjahfdhjajagdkffsdfjjlsksklgkshfjkjdajkddlj'], 46),
    ([5, 'aabab'], 5),
    ([16, 'abcdabcdabcdabcd'], 9),
    ([7, 'zabcabc'], 7),
    ([8, 'abcdeabc'], 8),
    ([11, 'ababcabcabc'], 10),
    ([8, 'ffffffff'], 5),
    ([8, 'abbababa'], 8),
    ([13, 'aabaabaabaabx'], 8),
    ([9, 'abcabcabc'], 7),
    ([99,
    'lhgjlskfgldjgadhdjjgskgakslflalhjfgfaaalkfdfgdkdffdjkjddfgdhalklhsgslskfdhsfjlhgajlgdfllhlsdhlhadaa'],
    99),
    ([1, 's'], 1),
    ([87,
    'fhjgjjagajllljffggjjhgfffhfkkaskksaalhksfllgdjsldagshhlhhgslhjaaffkahlskdagsfasfkgdfjka'],
    87),
    ([8, 'asafaass'], 8),
    ([14, 'abcabcabcabcjj'], 9),
    ([5, 'ababa'], 4),
    ([8, 'baaaaaaa'], 8),
    ([10, 'adadadadad'], 7),
    ([12, 'aabaabaabaab'], 7),
    ([6, 'abcbcd'], 6),
    ([7, 'abacbac'], 7),
    ([8, 'pppppppp'], 5),
    ([11, 'abcdeabcdfg'], 11),
    ([5, 'abcab'], 5),
    ([5, 'abbbb'], 5),
    ([7, 'aabcdaa'], 7),
    ([6, 'ababbb'], 5),
    ([8, 'aaabcabc'], 8),
    ([81,
    'aaaaaababaabaaaabaaaaaaaabbabbbbbabaabaabbaaaababaabaababbbabbaababababbbbbabbaaa'],
    79),
    ([10, 'aaaacaaaac'], 6),
    ([12, 'abaabaabaaba'], 7),
    ([92,
    'bbbbbabbbaaaabaaababbbaabbaabaaabbaabababaabbaabaabbbaabbaaabaabbbbaabbbabaaabbbabaaaaabaaaa'],
    91),
    ([9, 'azxcvzxcv'], 9),
    ([8, 'abcabcde'], 6),
    ([70,
    'babababbabababbbabaababbababaabaabbaaabbbbaababaabaabbbbbbaaabaabbbabb'],
    64),
    ([7, 'abcdabc'], 7),
    ([36, 'bbabbaabbbabbbbbabaaabbabbbabaabbbab'], 34),
    ([12, 'ababababbbbb'], 9),
    ([8, 'acacacac'], 5),
    ([66, 'ldldgjllllsdjgllkfljsgfgjkflakgfsklhdhhallggagdkgdgjggfshagjgkdfld'],
    65),
    ([74,
    'ghhhfaddfslafhhshjflkjdgksfashhllkggllllsljlfjsjhfggkgjfalgajaldgjfghlhdsh'],
    74),
    ([29, 'abbabbaabbbbaababbababbaabbaa'], 27),
    ([5, 'xabab'], 5),
    ([10, 'bbbbbbbaaa'], 8),
    ([3, 'lsl'], 3),
    ([32, 'bbbbaaabbaabbaabbabaaabaabaabaab'], 31),
    ([16, 'uuuuuuuuuuuuuuuu'], 9),
    ([37, 'lglfddsjhhaagkakadffkllkaagdaagdfdahg'], 37),
    ([45, 'bbbbbbbabababbbaabbbbbbbbbbbbabbbabbaabbbabab'], 43),
    ([12, 'wwvwwvwwvwwv'], 7),
    ([14, 'aaabcabcabcabc'], 14),
    ([95,
    'bbaaaabaababbbabaaaabababaaaaaabbababbaabbaaabbbaaaabaaaaaaababababbabbbaaaabaabaababbbbbababaa'],
    95),
    ([4, 'ttob'], 4),
    ([5, 'cabab'], 5),
    ([79,
    'lsfgfhhhkhklfdffssgffaghjjfkjsssjakglkajdhfkasfdhjhlkhsgsjfgsjghglkdkalaajsfdka'],
    79),
    ([11, 'jjlkalfhdhh'], 11),
    ([39, 'jflfashaglkahldafjasagasjghjkkjgkgffgkk'], 39),
    ([54, 'dgafkhlgdhjflkdafgjldjhgkjllfallhsggaaahkaggkhgjgflsdg'], 54),
    ([41, 'abbababbbbbabbbabaaaababaaabaabaaabbbbbbb'], 41),
    ([8, 'baaaaaab'], 8),
    ([36, 'babbbbababaaabbabbbaabaabbbbbbbbbbba'], 36),
    ([10, 'wvwlwvwwvw'], 10),
    ([38, 'asdsssdssjajghslfhjdfdhhdggdsdfsfajfas'], 38),
    ([77,
    'babbaababaabbaaaabbaababbbabaaaabbabaaaaaaaabbbaaabbabbbabaababbabaabbbbaaabb'],
    77),
    ([7, 'mabcabc'], 7),
    ([86,
    'ssjskldajkkskhljfsfkjhskaffgjjkskgddfslgjadjjgdjsjfsdgdgfdaldffjkakhhdaggalglakhjghssg'],
    86),
    ([20, 'ccbbcbaabcccbabcbcaa'], 20),
    ([8, 'abababaa'], 7),
    ([5, 'aabaa'], 5),
    ([13, 'eabcdefabcdef'], 13),
    ([28, 'aaaaaaaaaaaaaaibfprdokxvipsq'], 22),
    ([10, 'asdasdasda'], 8),
    ([8, 'aaaabcde'], 7),
    ([9, 'abbbbabbb'], 9),
    ([12, 'ababababvvvv'], 9),
    ([7, 'aabcabc'], 7)
]